export type PortfolioItem = { title: string; alt: string; src: string; cat: string; loc: string; };

export const portfolioItems: PortfolioItem[] = [
  { cat: "Airbnb",      title: "Muleshoe Art Loft — Street View",             loc: "Muleshoe, TX",  alt: "Exterior of the Muleshoe Art Loft Airbnb, a short-term rental on a quiet street in Muleshoe, TX.",                               src: "/images/portfolio/muleshoe-art-loft/exterior-street-view.jpg" },
  { cat: "Airbnb",      title: "Muleshoe Art Loft — Unit 1 Interior",         loc: "Muleshoe, TX",  alt: "Interior of Unit 1 at the Muleshoe Art Loft Airbnb featuring open-plan living with exposed structure and gallery styling.",      src: "/images/portfolio/muleshoe-art-loft/unit-1-interior.jpg" },
  { cat: "Airbnb",      title: "Muleshoe Art Loft — Unit 2 Detail",           loc: "Muleshoe, TX",  alt: "Interior detail shot of Unit 2 at the Muleshoe Art Loft Airbnb showing styled retail shelving and interior finishes.",          src: "/images/portfolio/muleshoe-art-loft/unit-2-detail.jpg" },
  { cat: "Real Estate", title: "Levelland Ranch Home — Exterior",             loc: "Levelland, TX", alt: "Single-story brick ranch home exterior in Levelland, TX with attached garage, photographed in hand-blended HDR.",               src: "/images/portfolio/levelland-ranch/exterior-front.jpg" },
  { cat: "Real Estate", title: "Levelland Ranch — Living Room",               loc: "Levelland, TX", alt: "Bright open living room in a Levelland, TX ranch listing with natural light and clear sightline to the kitchen.",               src: "/images/portfolio/levelland-ranch/living-room.jpg" },
  { cat: "Real Estate", title: "Levelland Ranch — Kitchen",                   loc: "Levelland, TX", alt: "Updated kitchen in a Levelland, TX ranch listing with stainless appliances, tiled backsplash, and window light.",               src: "/images/portfolio/levelland-ranch/kitchen.jpg" },
  { cat: "Real Estate", title: "Levelland Ranch — Kitchen and Dining",        loc: "Levelland, TX", alt: "Kitchen opening into a dining area in a Levelland, TX ranch home with tile floors and neutral cabinetry.",                      src: "/images/portfolio/levelland-ranch/kitchen-dining.jpg" },
  { cat: "Real Estate", title: "Muleshoe Brick Ranch — Exterior",             loc: "Muleshoe, TX",  alt: "Low-profile brick ranch exterior in Muleshoe, TX framed by mature trees, shot in hand-blended HDR.",                            src: "/images/portfolio/muleshoe-brick-ranch/exterior-front.jpg" },
  { cat: "Real Estate", title: "Muleshoe Open-Concept Home — Living Room",    loc: "Muleshoe, TX",  alt: "Bright living room with open sightlines to the dining area and natural window light in a Muleshoe, TX listing.",                src: "/images/portfolio/muleshoe-open-concept/living-room.jpg" },
  { cat: "Real Estate", title: "Muleshoe Brick Ranch — Kitchen",              loc: "Muleshoe, TX",  alt: "Full kitchen in a Muleshoe, TX listing with wood cabinetry, pendant lighting, and island seating.",                             src: "/images/portfolio/muleshoe-brick-ranch/kitchen.jpg" },
  { cat: "Real Estate", title: "Muleshoe Open-Concept Home — Dining & Living",loc: "Muleshoe, TX",  alt: "Open-concept dining area flowing into the living room in a Muleshoe, TX listing, shot in hand-blended HDR.",                   src: "/images/portfolio/muleshoe-open-concept/dining-living.jpg" },
  { cat: "Real Estate", title: "Muleshoe Brick Ranch — Primary Bedroom",      loc: "Muleshoe, TX",  alt: "Primary bedroom suite in a Muleshoe, TX listing with neutral palette, crown molding, and natural window light.",                 src: "/images/portfolio/muleshoe-brick-ranch/primary-bedroom.jpg" },
  { cat: "Real Estate", title: "Muleshoe Open-Concept Home — Kitchen Detail", loc: "Muleshoe, TX",  alt: "Kitchen detail in a Muleshoe, TX listing highlighting cabinetry finish and counter layout.",                                     src: "/images/portfolio/muleshoe-open-concept/kitchen-detail.jpg" },
  { cat: "Real Estate", title: "Muleshoe Brick Ranch — Primary Bath",         loc: "Muleshoe, TX",  alt: "Primary bathroom in a Muleshoe, TX listing with double vanity, neutral tile, and soaking tub.",                                  src: "/images/portfolio/muleshoe-brick-ranch/primary-bath.jpg" },
  { cat: "Real Estate", title: "Muleshoe Open-Concept Home — Kitchen Bar",    loc: "Muleshoe, TX",  alt: "Kitchen breakfast bar with counter seating in a Muleshoe, TX listing, photographed for MLS use.",                                src: "/images/portfolio/muleshoe-open-concept/kitchen-bar.jpg" },
  { cat: "Real Estate", title: "Muleshoe Brick Ranch — Formal Dining",        loc: "Muleshoe, TX",  alt: "Formal dining room in a Muleshoe, TX listing with chandelier, wood table setting, and neutral walls.",                           src: "/images/portfolio/muleshoe-brick-ranch/formal-dining.jpg" },
];
